app.version=2026.1.0
ios.support.version=2025.1.0
android.support.version=2025.1.0

# Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${PBC_MAIL_USERNAME}
spring.mail.password=${PBC_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## File Storage Properties
file.file-dir=./build/tmp/export-files