app.version=2026.5.4
ios.support.version=2025.1.0
android.support.version=2025.1.0

# Email properties
## Common SMTP Settings
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## Email Notifier - Event
mail.event.username=${PBC_MAIL_EVENT_NOTIFIER_USERNAME}
mail.event.password=${PBC_MAIL_EVENT_NOTIFIER_PASSWORD}

## Email Notifier - Info
mail.info.username=${PBC_MAIL_INFO_NOTIFIER_USERNAME}
mail.info.password=${PBC_MAIL_INFO_NOTIFIER_PASSWORD}

## Email Notifier - Broadcast
mail.broadcast.username=${PBC_MAIL_BROADCAST_NOTIFIER_USERNAME}
mail.broadcast.password=${PBC_MAIL_BROADCAST_NOTIFIER_PASSWORD}

## File Storage Properties
file.file-dir=./build/tmp/export-files