app.version=2025.1.0
ios.support.version=2025.1.0
android.support.version=2025.1.0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pbclive.digital@gmail.com
spring.mail.password=ddfpwxrxcmmbrtfi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true