package com.kavi.pbc.live.com.kavi.pbc.live.integration.firebase.datastore

object DatastoreConstant {
    const val CONFIG_COLLECTION = "CONFIG"
    const val USER_COLLECTION = "USER"
    const val USER_PUSH_TOKEN_COLLECTION = "USER_PUSH_TOKEN"
    const val EVENT_COLLECTION = "EVENT"
    const val EVENT_REGISTRATION_COLLECTION = "EVENT_REGISTRATION"
    const val EVENT_POTLUCK_COLLECTION = "EVENT_POTLUCK_COLLECTION"
    const val NEWS_COLLECTION = "NEWS"
    const val TOKEN_COLLECTION = "AUTH_TOKEN"
    const val QUESTION_COLLECTION = "QUESTION"
    const val APPOINTMENT_COLLECTION = "APPOINTMENT_COLLECTION"
    const val APPOINTMENT_REQUEST_COLLECTION = "APPOINTMENT_REQUEST_COLLECTION"
}